dog_labels_categories = {
    30: "Chihuahua",
    62: "Japanese Spaniel",
    73: "Maltese",
    85: "Pekinese",
    100: "Shih Tzu",
    14: "Blenheim Spaniel",
    84: "Papillion",
    111: "Toy Terrier",
    90: "Rhodesian Ridgeback",
    1: "Afghan Hound",
    9: "Basset Hound",
    10: "Beagle",
    15: "Bloodhound",
    16: "Bluetick",
    13: "Black And Tan Coonhound",
    113: "Walker Hound",
    40: "English Foxhound",
    89: "Redbone",
    19: "Borzoi",
    60: "Irish Wolfhound",
    61: "Italian Greyhound",
    117: "Whippet",
    56: "Ibizan Hound",
    80: "Norwegian Elkhound",
    83: "Otterhound",
    93: "Saluki",
    97: "Scottish Deerhound",
    114: "Weimaraner",
    104: "Staffordshire Bullterrier",
    5: "American Staffordshire Terrier",
    11: "Bedlington Terrier",
    18: "Border Terrier",
    65: "Kerry Blue Terrier",
    58: "Irish Terrier",
    79: "Norfolk Terrier",
    81: "Norwich Terrier",
    119: "Yorkshire Terrier",
    118: "Wirehaired Fox Terrier",
    69: "Lakeland Terrier",
    98: "Sealyham Terrier",
    3: "Airedale",
    27: "Cairn",
    7: "Australian Terrier",
    36: "Dandie Dinmont",
    20: "Boston Bulldog",
    77: "Miniature Schnauzer",
    49: "Giant Schnauzer",
    106: "Standard Schnauzer",
    96: "Scotch Terrier",
    109: "Tibetan Terrier",
    102: "Silky Terrier",
    103: "Soft Coated Wheaten Terrier",
    116: "West Highland White Terrier",
    71: "Lhasa Apso",
    45: "Flat Coated Retriever",
    35: "Curly Coated Retriever",
    50: "Golden Retriever",
    68: "Labrador Retriever",
    29: "Chesapeake Bay Retriever",
    48: "German Short Haired Pointer",
    112: "Vizsla",
    41: "English Setter",
    57: "Irish Setter",
    51: "Gordon Setter",
    25: "Brittany Spaniel",
    32: "Clumber",
    42: "English Springer",
    115: "Welsh Springer Spaniel",
    33: "Cocker Spaniel",
    107: "Sussex Spaniel",
    59: "Irish Water Spaniel",
    67: "Kuvasz",
    95: "Schipperke",
    55: "Groenendael",
    72: "Malinois",
    24: "Briard",
    64: "Kelpie",
    66: "Komondor",
    82: "Old English Sheepdog",
    99: "Shetland Sheepdog",
    34: "Collie",
    17: "Border Collie",
    21: "Bouvier Des Flandres",
    91: "Rottweiler",
    47: "German Shephard",
    39: "Doberman",
    75: "Miniature Pinscher",
    54: "Great Swiss Mountain Dog",
    12: "Bernese Mountain Dog",
    6: "Appenzeller",
    43: "EntleBucher",
    22: "Boxer",
    26: "Bull Mastiff",
    108: "Tibetan Mastiff",
    46: "French Bulldog",
    52: "Great Dane",
    92: "Saint Bernard",
    44: "Eskimo Dog",
    4: "Alaskan Malamute",
    101: "Siberian Husky",
    0: "Affenpinscher",
    8: "Basenji",
    88: "Pug",
    70: "Leonberg",
    78: "Newfoundland Terrier",
    53: "Great Pyrenees",
    94: "Samoyed",
    87: "Pomeranian",
    31: "Chow",
    63: "Keeshond",
    23: "Brabancon Griffon",
    86: "Pembroke Corgi",
    28: "Cardigan Corgi",
    110: "Toy Poodle",
    76: "Miniature Poodle",
    105: "Standard Poodle",
    74: "Mexican Hairless",
    38: "Dingo",
    37: "Dhole",
    2: "African Hunting Dog"
}